name: dev
channels:
  - defaults
dependencies:
  - attrs=21.2.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - iniconfig=1.1.1
  - libffi=3.3
  - more-itertools=8.10.0
  - ncurses=6.2
  - openssl=1.1.1l
  - packaging=21.3
  - pip=21.2.4
  - pluggy=0.13.1
  - py=1.10.0
  - pyparsing=3.0.4
  - pytest=6.2.4
  - python=3.9.6
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.36.0
  - tk=8.6.10
  - toml=0.10.2
  - tzdata=2021a
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - pip:
    - hiyapyco==0.4.16
    - jinja2==2.11.3
    - markupsafe==2.0.1
    - pyyaml==6.0
    - libcxx=10.0.0
